"""
Unit and Integration Tests for AI Career Guide
Tests all routes, score calculations, fallback mechanisms, and API endpoints.
"""

import unittest
import json
from app import app
from services.ai_service import generate_ai_preference_profile


class TestAICareerGuide(unittest.TestCase):

    def setUp(self):
        self.client = app.test_client()
        self.client.testing = True
        # Clear the global results cache so tests do not leak state
        import app as app_module
        app_module.GLOBAL_RESULTS_CACHE.clear()

    def test_landing_page(self):
        """Verify the landing page loads successfully."""
        response = self.client.get("/")
        self.assertEqual(response.status_code, 200)
        self.assertIn(b"AI Career Guide", response.data)
        self.assertIn(b"Discover your strengths", response.data)
        self.assertIn(b"How It Works", response.data)

    def test_assessment_page(self):
        """Verify the multi-step assessment page loads."""
        response = self.client.get("/assessment")
        self.assertEqual(response.status_code, 200)
        self.assertIn(b"Career Assessment", response.data)
        self.assertIn(b"Education Level", response.data)
        self.assertIn(b"Tell Us About Yourself", response.data)

    def test_results_page_requires_profile(self):
        """Verify results do not depend on a sample profile."""
        response = self.client.get("/results")
        self.assertEqual(response.status_code, 302)
        self.assertIn("/assessment", response.headers["Location"])

    def test_career_detail_requires_profile(self):
        """Verify career details do not depend on a sample profile."""
        response = self.client.get("/career/machine-learning-engineer")
        self.assertEqual(response.status_code, 302)
        self.assertIn("/assessment", response.headers["Location"])

    def test_dynamic_question_requires_configured_ai(self):
        """Verify dynamic questions are served by the AI endpoint rather than static content."""
        response = self.client.post(
            "/api/generate-question",
            data=json.dumps({"question_number": 1, "profile": {}, "previous_questions": [], "previous_answers": {}}),
            content_type="application/json"
        )
        self.assertIn(response.status_code, (200, 503))

    def test_calculate_profile_endpoint(self):
        """Verify the preference profile is generated by the AI service."""
        import app as app_module
        original = app_module.generate_ai_preference_profile
        app_module.generate_ai_preference_profile = lambda profile, questions, answers: {
            "analytical": 70, "technical": 80, "creative": 55, "social": 45,
            "leadership": 50, "research": 65, "practical": 60
        }
        try:
            response = self.client.post(
                "/api/calculate-profile",
                data=json.dumps({
                    "profile": {"skills": [{"name": "Python", "level": "Intermediate"}]},
                    "answers": {"q1": "a"},
                    "questions": [{"id": "q1", "question": "Example", "options": [{"value": "a", "label": "Example"}]}]
                }),
                content_type="application/json"
            )
            self.assertEqual(response.status_code, 200)
            data = json.loads(response.data)
            self.assertEqual(data["status"], "success")
            self.assertIn("technical", data["career_profile"])
        finally:
            app_module.generate_ai_preference_profile = original

    def test_health_endpoint(self):
        """Verify healthcheck endpoint."""
        response = self.client.get("/health")
        self.assertEqual(response.status_code, 200)
        data = json.loads(response.data)
        self.assertEqual(data["status"], "healthy")

    def test_matric_question_endpoint(self):
        """Verify Matric-specific question generation is used for Matric profiles."""
        import app as app_module
        original = app_module.generate_matric_question
        app_module.generate_matric_question = lambda profile, prev_q, prev_a, num: {
            "id": f"q{num}",
            "question": "Your teacher asks the class to build a simple project. What do you do?",
            "options": [
                {"value": "a", "label": "Start building it on a computer"},
                {"value": "b", "label": "Draw a plan first"},
                {"value": "c", "label": "Ask friends to help"},
                {"value": "d", "label": "Look for examples online"}
            ]
        }
        try:
            response = self.client.post(
                "/api/generate-question",
                data=json.dumps({
                    "question_number": 1,
                    "profile": {"education": "Matric", "matric_group": "Science"},
                    "previous_questions": [],
                    "previous_answers": {}
                }),
                content_type="application/json"
            )
            self.assertEqual(response.status_code, 200)
            data = json.loads(response.data)
            self.assertEqual(data["status"], "success")
            self.assertEqual(data["question"]["id"], "q1")
        finally:
            app_module.generate_matric_question = original

    def test_bachelors_requires_skills(self):
        """Verify Bachelor's users still need at least one skill."""
        response = self.client.post(
            "/api/analyze-career",
            data=json.dumps({
                "full_name": "Sara Ahmad",
                "education": "Undergraduate",
                "skills": [],
                "answers": {},
                "questions": []
            }),
            content_type="application/json"
        )
        self.assertEqual(response.status_code, 400)
        data = json.loads(response.data)
        self.assertEqual(data["status"], "error")
        self.assertIn("Please add at least one skill with a skill level.", data["message"])

    def test_matric_analysis_endpoint_and_results(self):
        """Verify Matric analysis returns study-path data and renders the Matric results view."""
        import app as app_module
        original = app_module.analyze_matric_study_path
        app_module.analyze_matric_study_path = lambda profile, questions, answers: {
            "is_matric": True,
            "recommended_path": {
                "title": "ICS",
                "reason": "You enjoy working with computers and scored well in Computer Science."
            },
            "other_options": [
                {"title": "FSc Pre-Engineering", "reason": "Your Maths and Physics marks are strong."},
                {"title": "ICom", "reason": "You also showed interest in business-related work."}
            ],
            "future_careers": [
                {"title": "Software Engineer", "description": "Build apps, websites, and software."},
                {"title": "Web Developer", "description": "Create and maintain websites."}
            ],
            "roadmap": ["Matric", "ICS", "BS Computer Science", "Software Engineer"],
            "career_profile": {
                "analytical": 0, "technical": 0, "creative": 0,
                "social": 0, "leadership": 0, "research": 0, "practical": 0
            }
        }
        try:
            response = self.client.post(
                "/api/analyze-career",
                data=json.dumps({
                    "full_name": "Ali Khan",
                    "education": "Matric",
                    "skills": [],
                    "answers": {"q1": "a"},
                    "questions": [{"id": "q1", "question": "Q", "options": [{"value": "a", "label": "A"}]}],
                    "matric_group": "Science",
                    "percentage": "85"
                }),
                content_type="application/json"
            )
            self.assertEqual(response.status_code, 200)
            data = json.loads(response.data)
            self.assertEqual(data["status"], "success")
            self.assertTrue(data["data"]["is_matric"])
            self.assertEqual(data["data"]["recommended_path"]["title"], "ICS")

            # Verify the Matric-specific error about skills is NOT returned
            self.assertNotIn(b"Please add at least one skill with a skill level.", response.data)

            # Verify the results page renders the Matric-specific template
            results_response = self.client.get("/results")
            self.assertEqual(results_response.status_code, 200)
            self.assertIn(b"Your Recommended Intermediate Path", results_response.data)
            self.assertIn(b"Student Profile Summary", results_response.data)
            self.assertIn(b"Education Path Analysis", results_response.data)
            self.assertIn(b"ICS", results_response.data)
            self.assertIn(b"Software Engineer", results_response.data)
        finally:
            app_module.analyze_matric_study_path = original

    def test_fsc_question_endpoint(self):
        """Verify FSc-specific question generation is used for FSc profiles."""
        import app as app_module
        original = app_module.generate_fsc_question
        app_module.generate_fsc_question = lambda profile, prev_q, prev_a, num: {
            "id": f"q{num}",
            "question": "Your college professor asks you to lead a project. What do you do first?",
            "options": [
                {"value": "a", "label": "Write code to build a prototype"},
                {"value": "b", "label": "Research existing solutions"},
                {"value": "c", "label": "Organize the team and assign tasks"},
                {"value": "d", "label": "Sketch a creative design"}
            ]
        }
        try:
            response = self.client.post(
                "/api/generate-question",
                data=json.dumps({
                    "question_number": 1,
                    "profile": {"education": "FSc / Intermediate", "fsc_group": "Pre-Engineering"},
                    "previous_questions": [],
                    "previous_answers": {}
                }),
                content_type="application/json"
            )
            self.assertEqual(response.status_code, 200)
            data = json.loads(response.data)
            self.assertEqual(data["status"], "success")
            self.assertEqual(data["question"]["id"], "q1")
        finally:
            app_module.generate_fsc_question = original

    def test_fsc_does_not_require_skills(self):
        """Verify FSc students are NOT required to have skills."""
        import app as app_module
        original = app_module.analyze_fsc_study_path
        app_module.analyze_fsc_study_path = lambda profile, questions, answers: {
            "is_fsc": True,
            "recommended_path": {"title": "BS Computer Science", "reason": "Good fit."},
            "other_options": [{"title": "BS IT", "reason": "Alternative."}],
            "future_careers": [{"title": "Developer", "description": "Build software."}],
            "roadmap": ["FSc", "BS CS", "Job"],
            "career_profile": {
                "analytical": 0, "technical": 0, "creative": 0,
                "social": 0, "leadership": 0, "research": 0, "practical": 0
            }
        }
        try:
            response = self.client.post(
                "/api/analyze-career",
                data=json.dumps({
                    "full_name": "Ahmed Raza",
                    "education": "FSc / Intermediate",
                    "skills": [],
                    "answers": {"q1": "a"},
                    "questions": [{"id": "q1", "question": "Q", "options": [{"value": "a", "label": "A"}]}],
                    "fsc_group": "ICS",
                    "college": "Punjab College"
                }),
                content_type="application/json"
            )
            self.assertEqual(response.status_code, 200)
            data = json.loads(response.data)
            self.assertEqual(data["status"], "success")
            # Should NOT get the skills error
            self.assertNotIn("skill", data.get("message", "").lower())
        finally:
            app_module.analyze_fsc_study_path = original

    def test_fsc_analysis_endpoint_and_results(self):
        """Verify FSc analysis returns degree-path data and renders the FSc results view."""
        import app as app_module
        original = app_module.analyze_fsc_study_path
        app_module.analyze_fsc_study_path = lambda profile, questions, answers: {
            "is_fsc": True,
            "recommended_path": {
                "title": "BS Computer Science",
                "reason": "Your ICS background and strong Maths score make CS ideal."
            },
            "other_options": [
                {"title": "BS Software Engineering", "reason": "Your coding interest aligns well."},
                {"title": "BS Data Science", "reason": "Your analytical thinking suits data work."}
            ],
            "future_careers": [
                {"title": "Software Engineer", "description": "Build apps and systems."},
                {"title": "Data Scientist", "description": "Analyze data to find insights."}
            ],
            "roadmap": ["FSc / Intermediate", "BS Computer Science (4 years)", "Internship", "Software Engineer"],
            "career_profile": {
                "analytical": 0, "technical": 0, "creative": 0,
                "social": 0, "leadership": 0, "research": 0, "practical": 0
            }
        }
        try:
            response = self.client.post(
                "/api/analyze-career",
                data=json.dumps({
                    "full_name": "Fatima Zahra",
                    "education": "FSc / Intermediate",
                    "skills": [],
                    "answers": {"q1": "a"},
                    "questions": [{"id": "q1", "question": "Q", "options": [{"value": "a", "label": "A"}]}],
                    "fsc_group": "ICS",
                    "college": "Government College",
                    "percentage": "82",
                    "favourite_subject": "Computer Science",
                    "strongest_subject": "Maths",
                    "interests_hobbies": "Coding and reading"
                }),
                content_type="application/json"
            )
            self.assertEqual(response.status_code, 200)
            data = json.loads(response.data)
            self.assertEqual(data["status"], "success")
            self.assertTrue(data["data"]["is_fsc"])
            self.assertEqual(data["data"]["recommended_path"]["title"], "BS Computer Science")

            # Verify skills error is NOT returned
            self.assertNotIn(b"Please add at least one skill with a skill level.", response.data)

            # Verify the results page renders the FSc-specific template
            results_response = self.client.get("/results")
            self.assertEqual(results_response.status_code, 200)
            self.assertIn(b"Your Recommended Degree Program", results_response.data)
            self.assertIn(b"FSc / Intermediate Profile Summary", results_response.data)
            self.assertIn(b"Degree Path Analysis", results_response.data)
            self.assertIn(b"BS Computer Science", results_response.data)
            self.assertIn(b"Software Engineer", results_response.data)

            # Verify FSc profile fields are preserved in the results
            self.assertIn(b"Fatima Zahra", results_response.data)
            self.assertIn(b"ICS", results_response.data)
            self.assertIn(b"Government College", results_response.data)
        finally:
            app_module.analyze_fsc_study_path = original


if __name__ == "__main__":
    unittest.main()
